language: java
os: linux
sudo: true

script:
  - sudo apt-get install build-essential cmake
  - cd MockBridgeFarmer-C
  - mkdir build
  - cd build
  - cmake ..
  - ./MockBridgeFarmer
  - cd ../..
  - mvn clean test -Dtest=Verify*
